// Copyright (c) 2022 Mikael Simonsson <https://mikaelsimonsson.com>.
// SPDX-License-Identifier: BSL-1.0

#include "snn-core/time/duration.formatter.hh"

#include "snn-core/unittest.hh"
#include "snn-core/fmt/format.hh"

namespace snn::app
{
    namespace
    {
        bool example()
        {
            snn_require(fmt::format("{}", time::duration{0, 0}) == "0s");
            snn_require(fmt::format("{}", time::duration{0, 12345}) == "12.345µs");
            snn_require(fmt::format("{}", time::duration{3599, 222}) == "59m59.000000222s");
            snn_require(fmt::format("{}", time::duration{90000, 500000000}) == "25h0.5s");

            return true;
        }

        bool test_fmt_format()
        {
            // Generated by: detail/duration.formatter.test.gen.go

            snn_require(fmt::format("{}", time::duration{0, 0}) == "0s");

            snn_require(fmt::format("{}", time::duration{0, 1}) == "1ns");
            snn_require(fmt::format("{}", time::duration{0, 10}) == "10ns");
            snn_require(fmt::format("{}", time::duration{0, 100}) == "100ns");
            snn_require(fmt::format("{}", time::duration{0, 1000}) == "1µs");
            snn_require(fmt::format("{}", time::duration{0, 10000}) == "10µs");
            snn_require(fmt::format("{}", time::duration{0, 100000}) == "100µs");
            snn_require(fmt::format("{}", time::duration{0, 1000000}) == "1ms");
            snn_require(fmt::format("{}", time::duration{0, 10000000}) == "10ms");
            snn_require(fmt::format("{}", time::duration{0, 100000000}) == "100ms");

            snn_require(fmt::format("{}", time::duration{0, 1}) == "1ns");
            snn_require(fmt::format("{}", time::duration{0, 12}) == "12ns");
            snn_require(fmt::format("{}", time::duration{0, 123}) == "123ns");
            snn_require(fmt::format("{}", time::duration{0, 1200}) == "1.2µs");
            snn_require(fmt::format("{}", time::duration{0, 12300}) == "12.3µs");
            snn_require(fmt::format("{}", time::duration{0, 123400}) == "123.4µs");
            snn_require(fmt::format("{}", time::duration{0, 1200000}) == "1.2ms");
            snn_require(fmt::format("{}", time::duration{0, 12300000}) == "12.3ms");
            snn_require(fmt::format("{}", time::duration{0, 123400000}) == "123.4ms");

            snn_require(fmt::format("{}", time::duration{0, 1}) == "1ns");
            snn_require(fmt::format("{}", time::duration{0, 12}) == "12ns");
            snn_require(fmt::format("{}", time::duration{0, 123}) == "123ns");
            snn_require(fmt::format("{}", time::duration{0, 1234}) == "1.234µs");
            snn_require(fmt::format("{}", time::duration{0, 12345}) == "12.345µs");
            snn_require(fmt::format("{}", time::duration{0, 123456}) == "123.456µs");
            snn_require(fmt::format("{}", time::duration{0, 1234567}) == "1.234567ms");
            snn_require(fmt::format("{}", time::duration{0, 12345678}) == "12.345678ms");
            snn_require(fmt::format("{}", time::duration{0, 123456789}) == "123.456789ms");

            snn_require(fmt::format("{}", time::duration{-1, 0}) == "-1s");

            snn_require(fmt::format("{}", time::duration{-1, 999999999}) == "-1ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999990}) == "-10ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999900}) == "-100ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999000}) == "-1µs");
            snn_require(fmt::format("{}", time::duration{-1, 999990000}) == "-10µs");
            snn_require(fmt::format("{}", time::duration{-1, 999900000}) == "-100µs");
            snn_require(fmt::format("{}", time::duration{-1, 999000000}) == "-1ms");
            snn_require(fmt::format("{}", time::duration{-1, 990000000}) == "-10ms");
            snn_require(fmt::format("{}", time::duration{-1, 900000000}) == "-100ms");

            snn_require(fmt::format("{}", time::duration{-1, 999999999}) == "-1ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999991}) == "-9ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999912}) == "-88ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999123}) == "-877ns");
            snn_require(fmt::format("{}", time::duration{-1, 999991234}) == "-8.766µs");
            snn_require(fmt::format("{}", time::duration{-1, 999912345}) == "-87.655µs");
            snn_require(fmt::format("{}", time::duration{-1, 999123456}) == "-876.544µs");
            snn_require(fmt::format("{}", time::duration{-1, 991234567}) == "-8.765433ms");
            snn_require(fmt::format("{}", time::duration{-1, 912345678}) == "-87.654322ms");

            snn_require(fmt::format("{}", time::duration{-1, 999999999}) == "-1ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999991}) == "-9ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999912}) == "-88ns");
            snn_require(fmt::format("{}", time::duration{-1, 999999123}) == "-877ns");
            snn_require(fmt::format("{}", time::duration{-1, 999991200}) == "-8.8µs");
            snn_require(fmt::format("{}", time::duration{-1, 999912300}) == "-87.7µs");
            snn_require(fmt::format("{}", time::duration{-1, 999123400}) == "-876.6µs");
            snn_require(fmt::format("{}", time::duration{-1, 991200000}) == "-8.8ms");
            snn_require(fmt::format("{}", time::duration{-1, 912300000}) == "-87.7ms");

            snn_require(fmt::format("{}", time::duration{3, 0}) == "3s");
            snn_require(fmt::format("{}", time::duration{3, 1}) == "3.000000001s");
            snn_require(fmt::format("{}", time::duration{3, 222}) == "3.000000222s");
            snn_require(fmt::format("{}", time::duration{3, 333444}) == "3.000333444s");
            snn_require(fmt::format("{}", time::duration{3, 123456000}) == "3.123456s");
            snn_require(fmt::format("{}", time::duration{3, 500000000}) == "3.5s");
            snn_require(fmt::format("{}", time::duration{3, 999999999}) == "3.999999999s");

            snn_require(fmt::format("{}", time::duration{-3, 0}) == "-3s");
            snn_require(fmt::format("{}", time::duration{-3, 1}) == "-2.999999999s");
            snn_require(fmt::format("{}", time::duration{-3, 222}) == "-2.999999778s");
            snn_require(fmt::format("{}", time::duration{-3, 333444}) == "-2.999666556s");
            snn_require(fmt::format("{}", time::duration{-3, 123456000}) == "-2.876544s");
            snn_require(fmt::format("{}", time::duration{-3, 500000000}) == "-2.5s");
            snn_require(fmt::format("{}", time::duration{-3, 999999999}) == "-2.000000001s");

            snn_require(fmt::format("{}", time::duration{59, 0}) == "59s");
            snn_require(fmt::format("{}", time::duration{59, 1}) == "59.000000001s");
            snn_require(fmt::format("{}", time::duration{59, 222}) == "59.000000222s");
            snn_require(fmt::format("{}", time::duration{59, 333444}) == "59.000333444s");
            snn_require(fmt::format("{}", time::duration{59, 123456000}) == "59.123456s");
            snn_require(fmt::format("{}", time::duration{59, 500000000}) == "59.5s");
            snn_require(fmt::format("{}", time::duration{59, 999999999}) == "59.999999999s");

            snn_require(fmt::format("{}", time::duration{60, 0}) == "1m");
            snn_require(fmt::format("{}", time::duration{60, 1}) == "1m0.000000001s");
            snn_require(fmt::format("{}", time::duration{60, 222}) == "1m0.000000222s");
            snn_require(fmt::format("{}", time::duration{60, 333444}) == "1m0.000333444s");
            snn_require(fmt::format("{}", time::duration{60, 123456000}) == "1m0.123456s");
            snn_require(fmt::format("{}", time::duration{60, 500000000}) == "1m0.5s");
            snn_require(fmt::format("{}", time::duration{60, 999999999}) == "1m0.999999999s");

            snn_require(fmt::format("{}", time::duration{61, 0}) == "1m1s");
            snn_require(fmt::format("{}", time::duration{61, 1}) == "1m1.000000001s");
            snn_require(fmt::format("{}", time::duration{61, 222}) == "1m1.000000222s");
            snn_require(fmt::format("{}", time::duration{61, 333444}) == "1m1.000333444s");
            snn_require(fmt::format("{}", time::duration{61, 123456000}) == "1m1.123456s");
            snn_require(fmt::format("{}", time::duration{61, 500000000}) == "1m1.5s");
            snn_require(fmt::format("{}", time::duration{61, 999999999}) == "1m1.999999999s");

            snn_require(fmt::format("{}", time::duration{-59, 0}) == "-59s");
            snn_require(fmt::format("{}", time::duration{-59, 1}) == "-58.999999999s");
            snn_require(fmt::format("{}", time::duration{-59, 222}) == "-58.999999778s");
            snn_require(fmt::format("{}", time::duration{-59, 333444}) == "-58.999666556s");
            snn_require(fmt::format("{}", time::duration{-59, 123456000}) == "-58.876544s");
            snn_require(fmt::format("{}", time::duration{-59, 500000000}) == "-58.5s");
            snn_require(fmt::format("{}", time::duration{-59, 999999999}) == "-58.000000001s");

            snn_require(fmt::format("{}", time::duration{-60, 0}) == "-1m");
            snn_require(fmt::format("{}", time::duration{-60, 1}) == "-59.999999999s");
            snn_require(fmt::format("{}", time::duration{-60, 222}) == "-59.999999778s");
            snn_require(fmt::format("{}", time::duration{-60, 333444}) == "-59.999666556s");
            snn_require(fmt::format("{}", time::duration{-60, 123456000}) == "-59.876544s");
            snn_require(fmt::format("{}", time::duration{-60, 500000000}) == "-59.5s");
            snn_require(fmt::format("{}", time::duration{-60, 999999999}) == "-59.000000001s");

            snn_require(fmt::format("{}", time::duration{-61, 0}) == "-1m1s");
            snn_require(fmt::format("{}", time::duration{-61, 1}) == "-1m0.999999999s");
            snn_require(fmt::format("{}", time::duration{-61, 222}) == "-1m0.999999778s");
            snn_require(fmt::format("{}", time::duration{-61, 333444}) == "-1m0.999666556s");
            snn_require(fmt::format("{}", time::duration{-61, 123456000}) == "-1m0.876544s");
            snn_require(fmt::format("{}", time::duration{-61, 500000000}) == "-1m0.5s");
            snn_require(fmt::format("{}", time::duration{-61, 999999999}) == "-1m0.000000001s");

            snn_require(fmt::format("{}", time::duration{3599, 0}) == "59m59s");
            snn_require(fmt::format("{}", time::duration{3599, 1}) == "59m59.000000001s");
            snn_require(fmt::format("{}", time::duration{3599, 222}) == "59m59.000000222s");
            snn_require(fmt::format("{}", time::duration{3599, 333444}) == "59m59.000333444s");
            snn_require(fmt::format("{}", time::duration{3599, 123456000}) == "59m59.123456s");
            snn_require(fmt::format("{}", time::duration{3599, 500000000}) == "59m59.5s");
            snn_require(fmt::format("{}", time::duration{3599, 999999999}) == "59m59.999999999s");

            snn_require(fmt::format("{}", time::duration{3600, 0}) == "1h");
            snn_require(fmt::format("{}", time::duration{3600, 1}) == "1h0.000000001s");
            snn_require(fmt::format("{}", time::duration{3600, 222}) == "1h0.000000222s");
            snn_require(fmt::format("{}", time::duration{3600, 333444}) == "1h0.000333444s");
            snn_require(fmt::format("{}", time::duration{3600, 123456000}) == "1h0.123456s");
            snn_require(fmt::format("{}", time::duration{3600, 500000000}) == "1h0.5s");
            snn_require(fmt::format("{}", time::duration{3600, 999999999}) == "1h0.999999999s");

            snn_require(fmt::format("{}", time::duration{3601, 0}) == "1h1s");
            snn_require(fmt::format("{}", time::duration{3601, 1}) == "1h1.000000001s");
            snn_require(fmt::format("{}", time::duration{3601, 222}) == "1h1.000000222s");
            snn_require(fmt::format("{}", time::duration{3601, 333444}) == "1h1.000333444s");
            snn_require(fmt::format("{}", time::duration{3601, 123456000}) == "1h1.123456s");
            snn_require(fmt::format("{}", time::duration{3601, 500000000}) == "1h1.5s");
            snn_require(fmt::format("{}", time::duration{3601, 999999999}) == "1h1.999999999s");

            snn_require(fmt::format("{}", time::duration{-3599, 0}) == "-59m59s");
            snn_require(fmt::format("{}", time::duration{-3599, 1}) == "-59m58.999999999s");
            snn_require(fmt::format("{}", time::duration{-3599, 222}) == "-59m58.999999778s");
            snn_require(fmt::format("{}", time::duration{-3599, 333444}) == "-59m58.999666556s");
            snn_require(fmt::format("{}", time::duration{-3599, 123456000}) == "-59m58.876544s");
            snn_require(fmt::format("{}", time::duration{-3599, 500000000}) == "-59m58.5s");
            snn_require(fmt::format("{}", time::duration{-3599, 999999999}) == "-59m58.000000001s");

            snn_require(fmt::format("{}", time::duration{-3600, 0}) == "-1h");
            snn_require(fmt::format("{}", time::duration{-3600, 1}) == "-59m59.999999999s");
            snn_require(fmt::format("{}", time::duration{-3600, 222}) == "-59m59.999999778s");
            snn_require(fmt::format("{}", time::duration{-3600, 333444}) == "-59m59.999666556s");
            snn_require(fmt::format("{}", time::duration{-3600, 123456000}) == "-59m59.876544s");
            snn_require(fmt::format("{}", time::duration{-3600, 500000000}) == "-59m59.5s");
            snn_require(fmt::format("{}", time::duration{-3600, 999999999}) == "-59m59.000000001s");

            snn_require(fmt::format("{}", time::duration{-3601, 0}) == "-1h1s");
            snn_require(fmt::format("{}", time::duration{-3601, 1}) == "-1h0.999999999s");
            snn_require(fmt::format("{}", time::duration{-3601, 222}) == "-1h0.999999778s");
            snn_require(fmt::format("{}", time::duration{-3601, 333444}) == "-1h0.999666556s");
            snn_require(fmt::format("{}", time::duration{-3601, 123456000}) == "-1h0.876544s");
            snn_require(fmt::format("{}", time::duration{-3601, 500000000}) == "-1h0.5s");
            snn_require(fmt::format("{}", time::duration{-3601, 999999999}) == "-1h0.000000001s");

            snn_require(fmt::format("{}", time::duration{90000, 0}) == "25h");
            snn_require(fmt::format("{}", time::duration{90000, 1}) == "25h0.000000001s");
            snn_require(fmt::format("{}", time::duration{90000, 222}) == "25h0.000000222s");
            snn_require(fmt::format("{}", time::duration{90000, 333444}) == "25h0.000333444s");
            snn_require(fmt::format("{}", time::duration{90000, 123456000}) == "25h0.123456s");
            snn_require(fmt::format("{}", time::duration{90000, 500000000}) == "25h0.5s");
            snn_require(fmt::format("{}", time::duration{90000, 999999999}) == "25h0.999999999s");

            snn_require(fmt::format("{}", time::duration{-90000, 0}) == "-25h");
            snn_require(fmt::format("{}", time::duration{-90000, 1}) == "-24h59m59.999999999s");
            snn_require(fmt::format("{}", time::duration{-90000, 222}) == "-24h59m59.999999778s");
            snn_require(fmt::format("{}", time::duration{-90000, 333444}) ==
                        "-24h59m59.999666556s");
            snn_require(fmt::format("{}", time::duration{-90000, 123456000}) ==
                        "-24h59m59.876544s");
            snn_require(fmt::format("{}", time::duration{-90000, 500000000}) == "-24h59m59.5s");
            snn_require(fmt::format("{}", time::duration{-90000, 999999999}) ==
                        "-24h59m59.000000001s");

            return true;
        }

        constexpr bool test_formatter()
        {
            formatter<time::duration> f;
            fmt::context ctx;

            strbuf append_to;

            f.format(time::duration{3599, 123456000}, "", ctx, append_to, assume::no_overlap);
            snn_require(append_to == "59m59.123456s");

            f.format(time::duration{-1, 999912300}, "", ctx, append_to, assume::no_overlap);
            snn_require(append_to == "59m59.123456s-87.7µs");

            return true;
        }
    }
}

namespace snn
{
    void unittest()
    {
        snn_require(app::example());
        snn_require(app::test_fmt_format());
        snn_static_require(app::test_formatter());
    }
}
