// Copyright (c) 2022 Mikael Simonsson <https://mikaelsimonsson.com>.
// SPDX-License-Identifier: BSL-1.0 AND BSD-3-Clause
// Generated from encodings.json from WHATWG (see LICENSE.md).
// Copyright (c) WHATWG (Apple, Google, Mozilla, Microsoft).

// # Scheme (enum)

#pragma once

#include "snn-core/core.hh"

namespace snn::encoding
{
    // Generated by: detail/scheme.gen.cc

    // ## Enums

    // ### scheme

    enum class scheme : u8
    {
        unknown = 0,
        big5,
        euc_jp,
        euc_kr,
        gb18030,
        gbk,
        ibm866,
        iso2022jp,
        iso8859_1, // Not used by the WHATWG Encoding Standard (maps to windows1252).
        iso8859_10,
        iso8859_13,
        iso8859_14,
        iso8859_15,
        iso8859_16,
        iso8859_2,
        iso8859_3,
        iso8859_4,
        iso8859_5,
        iso8859_6,
        iso8859_7,
        iso8859_8,
        iso8859_8i,
        koi8r,
        koi8u,
        macintosh,
        replacement,
        shift_jis,
        utf16be,
        utf16le,
        utf8,
        windows1250,
        windows1251,
        windows1252,
        windows1253,
        windows1254,
        windows1255,
        windows1256,
        windows1257,
        windows1258,
        windows874,
        x_mac_cyrillic,
        x_user_defined, // Last (used below).
    };

    // ## Constants

    // ### scheme_count

    inline constexpr usize scheme_count = 42;
    static_assert(to_underlying(scheme::x_user_defined) == (scheme_count - 1));
}
