// Copyright (c) 2022 Mikael Simonsson <https://mikaelsimonsson.com>.
// SPDX-License-Identifier: BSL-1.0 AND BSD-3-Clause
// Generated from encodings.json from WHATWG (see LICENSE.md).
// Copyright (c) WHATWG (Apple, Google, Mozilla, Microsoft).

// # Scheme names (array)

#pragma once

#include "snn-core/array.hh"
#include "snn-core/size_prefixed_string_literal.hh"
#include "snn-core/encoding/scheme.hh"

namespace snn::encoding
{
    // Generated by: detail/scheme.gen.cc

    // ## Arrays

    // ### scheme_names

    // clang-format off
    inline constexpr array<size_prefixed_string_literal, scheme_count> scheme_names{
        "\007Unknown",
        "\004Big5",
        "\006EUC-JP",
        "\006EUC-KR",
        "\007gb18030",
        "\003GBK",
        "\006IBM866",
        "\013ISO-2022-JP",
        "\012ISO-8859-1", // Not used by the WHATWG Encoding Standard.
        "\013ISO-8859-10",
        "\013ISO-8859-13",
        "\013ISO-8859-14",
        "\013ISO-8859-15",
        "\013ISO-8859-16",
        "\012ISO-8859-2",
        "\012ISO-8859-3",
        "\012ISO-8859-4",
        "\012ISO-8859-5",
        "\012ISO-8859-6",
        "\012ISO-8859-7",
        "\012ISO-8859-8",
        "\014ISO-8859-8-I",
        "\006KOI8-R",
        "\006KOI8-U",
        "\011macintosh",
        "\013replacement",
        "\011Shift_JIS",
        "\010UTF-16BE",
        "\010UTF-16LE",
        "\005UTF-8",
        "\014windows-1250",
        "\014windows-1251",
        "\014windows-1252",
        "\014windows-1253",
        "\014windows-1254",
        "\014windows-1255",
        "\014windows-1256",
        "\014windows-1257",
        "\014windows-1258",
        "\013windows-874",
        "\016x-mac-cyrillic",
        "\016x-user-defined",
    };
    // clang-format on
}
