// Copyright (c) 2022 Mikael Simonsson <https://mikaelsimonsson.com>.
// SPDX-License-Identifier: BSL-1.0 AND BSD-3-Clause
// Generated from encodings.json from WHATWG (see LICENSE.md).
// Copyright (c) WHATWG (Apple, Google, Mozilla, Microsoft).

// # Schemes (array)

#pragma once

#include "snn-core/array.hh"
#include "snn-core/encoding/scheme.hh"

namespace snn::encoding
{
    // Generated by: detail/scheme.gen.cc

    // ## Arrays

    // ### schemes

    // clang-format off
    inline constexpr array<scheme, scheme_count> schemes{
        scheme::unknown,
        scheme::big5,
        scheme::euc_jp,
        scheme::euc_kr,
        scheme::gb18030,
        scheme::gbk,
        scheme::ibm866,
        scheme::iso2022jp,
        scheme::iso8859_1, // Not used by the WHATWG Encoding Standard.
        scheme::iso8859_10,
        scheme::iso8859_13,
        scheme::iso8859_14,
        scheme::iso8859_15,
        scheme::iso8859_16,
        scheme::iso8859_2,
        scheme::iso8859_3,
        scheme::iso8859_4,
        scheme::iso8859_5,
        scheme::iso8859_6,
        scheme::iso8859_7,
        scheme::iso8859_8,
        scheme::iso8859_8i,
        scheme::koi8r,
        scheme::koi8u,
        scheme::macintosh,
        scheme::replacement,
        scheme::shift_jis,
        scheme::utf16be,
        scheme::utf16le,
        scheme::utf8,
        scheme::windows1250,
        scheme::windows1251,
        scheme::windows1252,
        scheme::windows1253,
        scheme::windows1254,
        scheme::windows1255,
        scheme::windows1256,
        scheme::windows1257,
        scheme::windows1258,
        scheme::windows874,
        scheme::x_mac_cyrillic,
        scheme::x_user_defined,
    };
    // clang-format on
}
